name: Deploy Web4U to GitHub Pages

on:
  push:
    branches:
      - main # Asegúrate de que esta es tu rama principal

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Pages ⚙️
        uses: actions/configure-pages@v5

      - name: Upload Artifact 📦
        uses: actions/upload-pages-artifact@v3
        with:
          # ¡Punto clave! Esto publica el contenido de tu carpeta Web4U
          path: 'Web4U'

      - name: Deploy to GitHub Pages 🚀
        id: deployment
        uses: actions/deploy-pages@v4
